### PR TITLE
Add materlized views, manual refresh option and minor fixes

### LINKED ISSUE #127: [FEATURE] Table Acceleration Support
Flint Spark extension to create skipping index with OpenSearch which can accelerate query with applicable filtering condition. 

### Skipping Index 
* User can only create, view or delete  a skipping index 
* One table can only have 1 skipping index for a Flint table
* Name is auto-generated for a given table and follows a pre-defined by a naming convention
* Columns can be accelerated individually using partition, value_set and min_max skipping type
* This is always auto-refreshed or manually refreshed. 
### Covering Index
* User can only create, view or delete a covering index 
* User can have multiple covering index for a Flint table 
* User can define their own name for the covering Index
* User can select columns required for creating the covering index
* This is always auto-refreshed or manually refreshed. 
### Materialized View
* User can only create, view or delete a materialised view 
* User can have multiple materialized views for a Flint table 
* User can define their own name for the materialized view
* Columns can be aggregated into metrics with different functions like count, min, max, sum and avg.  
* The above metrics can be further grouped into different columns [Ex. TUMBLE() or SLIDE()]
* Final check for MVs are where clauses to restrict metrics on a given subset of data
* This is always auto-refreshed or manually refreshed.

### PR DESCRIPTION
**Pull request by ps48**
### Description
1. Add materialized view option
2. remove fill from accelerate table button
3. Add manual refresh option
4. Update copy for data sources
5. Fix redirection issue to acceleration flyout
6. Update tests

 
### Issues Resolved
#127 
Depends on https://github.com/opensearch-project/opensearch-spark/pull/73
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: public/components/SQLPage/SQLPage.tsx [hunk 1]
```diff
@@ -37,6 +37,8 @@ interface SQLPageProps {
   sqlTranslations: ResponseDetail<TranslateResult>[];
   selectedDatasource: EuiComboBoxOptionOption[];
   asyncLoading: boolean;
+  openAccelerationFlyout: boolean;
```
Comment (derek-ho) [inline public/components/SQLPage/SQLPage.tsx:40]: Can we change this to something like isAccelerationFlyoutOpen

File: public/components/Main/main.tsx [hunk 2]
```diff
@@ -819,6 +827,10 @@ export class Main extends React.Component<MainProps, MainState> {
           updateSQLQueries={this.updateSQLQueries}
           selectedDatasource={this.state.selectedDatasource}
           asyncLoading={this.state.asyncLoading}
+          openAccelerationFlyout={
+            this.props.isAccelerationFlyoutOpen && !this.state.isAccelerationFlyoutOpened
```
Comment (derek-ho) [inline public/components/Main/main.tsx:831]: I don't quite get why these two booleans are used?

**Review by kavithacm — APPROVED** [review]

File: public/components/Main/main.tsx (hunk 2 above)
Comment (ps48) [reply public/components/Main/main.tsx:831]: One is for the prop which dictates if URL has a datasource that needs to be open with acceleration flyout. The other is to keep a local state. We need the local state to make sure, the URL flyout only opens once.

File: public/components/SQLPage/SQLPage.tsx (hunk 1 above)
Comment (ps48) [reply public/components/SQLPage/SQLPage.tsx:40]: `isAccelerationFlyoutOpen` doesn't make much sense as a name here. This prop dictates should be acceleration flyout be opened or not by the SQL page component. 
ex:
```
if parent props sends value openAccelerationFlyout={true} -> the child component opens the flyout

**Review by YANG-DB — APPROVED** [review]
