### PR TITLE
Fix error handling for user w/o proper permissions

### LINKED ISSUE #193: [BUG] Navigating to query workbench with no data sources permissions crashes the page
**What is the bug?**
`{
    "statusCode": 403,
    "error": "Forbidden",
    "message": "{\n  \"status\": 403,\n  \"error\": {\n    \"type\": \"OpenSearchSecurityException\",\n    \"reason\": \"There was internal problem at backend\",\n    \"details\": \"no permissions for [cluster:admin/opensearch/ql/datasources/read] and User [name\\u003dtest, backend_roles\\u003d[], requestedTenant\\u003d__user__]\"\n  }\n}"
}`

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by ps48**
### Description
Fix error handling for user w/o indices access and sql/ppl access 

### Issues Resolved
#193 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: public/components/SQLPage/table_view.tsx [hunk 1]
```diff
@@ -131,9 +131,9 @@ export const TableView = ({ http, selectedItems, updateSQLQueries, refreshTree }
           console.error(err);
           setIsLoading({
             flag: false,
-            status: err,
```
Comment (ps48) [inline public/components/SQLPage/table_view.tsx:134]: @sumukhswamy  This is was the line causing error leading to blank page.

**Review by derek-ho — APPROVED** [review]
Working better, still need to test this out some more

**Review by kavithacm — APPROVED** [review]
