### PR TITLE
added fix for loading spinner issue for other database

### LINKED ISSUE #190: [BUG] Overlapping rows when many tables
**What is the bug?**
Screenshot 2023-10-30 at 12 39 10 PM

Overlapping rows when many tables

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**

 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by sumukhswamy**
### Description
Fixed multiple toast for database
added fix for other database click
moved code to functions to reduce the repetition
 
### Issues Resolved
#190 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: public/components/SQLPage/table_view.tsx [hunk 1]
```diff
@@ -602,8 +565,11 @@ export const TableView = ({ http, selectedItems, updateSQLQueries, refreshTree }
       id: `${database.name}_${table.name}`,
       icon: iconCreation(table),
       callback: () => {
+        if(table.type === TREE_ITEM_LOAD_MATERIALIZED_BADGE_NAME){
+          handleButtonClick(table.name,database.name)
+        }
         if (table.type !== TREE_ITEM_LOAD_MATERIALIZED_BADGE_NAME && table.type !== TREE_ITEM_MATERIALIZED_VIEW_DEFAULT_NAME && table.values?.length === 0) {
-          handleTableClick(table.name);
+          handleTableClick(table.name,database.name);
```
Comment (ps48) [inline public/components/SQLPage/table_view.tsx:572]: can two Spark SQL tables and databases have same name? Can you please check this. 
If this happens how is it handled?

Comment (sumukhswamy) [reply public/components/SQLPage/table_view.tsx:572]: spark databases do not allow databases with same name to exist, same table name but different database is working fine

Comment (ps48) [reply public/components/SQLPage/table_view.tsx:572]: got it, can you please share some spark docs here? Also, a better way to deal this would be to have an unique id in the treeitem.

**Review by mengweieric — APPROVED** [review]

**Review by YANG-DB — APPROVED** [review]
